#!/usr/bin/env perl
# Applies homelab-worker's own migrations/*.sql via the migrate role.
# Same template as homelab-domain-admin-migrate -- see that file's comment.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Homelab::Common::Config qw(load_config);
use Homelab::Common::DB qw(migrate_dbh);
use Homelab::Common::Migrate qw(run_migrations);

my $config = load_config('HOMELAB_WORKER_CONFIG', '/etc/homelab/worker/config.yml');
my $dbh    = migrate_dbh(%{ $config->{database_migrate} });

my $migrations_dir = $ENV{HOMELAB_WORKER_MIGRATIONS_DIR} // '/usr/share/homelab-worker/migrations';
my $applied = run_migrations(dbh => $dbh, schema => 'worker', migrations_dir => $migrations_dir);

print "homelab-worker: applied $applied migration(s)\n";
