#!/usr/bin/env perl
# Applies homelab-invite's own migrations/*.sql via the migrate role.
# Same template as homelab-domain-admin-migrate -- see that file's
# comment.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Homelab::Common::Config qw(load_config);
use Homelab::Common::DB qw(migrate_dbh);
use Homelab::Common::Migrate qw(run_migrations);

my $config = load_config('HOMELAB_INVITE_CONFIG', '/etc/homelab/invite/config.yml');
my $dbh    = migrate_dbh(%{ $config->{database_migrate} });

my $migrations_dir = $ENV{HOMELAB_INVITE_MIGRATIONS_DIR} // '/usr/share/homelab-invite/migrations';
my $applied = run_migrations(dbh => $dbh, schema => 'invite', migrations_dir => $migrations_dir);

print "homelab-invite: applied $applied migration(s)\n";
