#!/bin/sh
set -e
case "$1" in
    purge)
        rm -f /etc/homelab/services/blackbox-exporter.yml
        rm -f /etc/prometheus/homelab/blackbox.yml /etc/prometheus/homelab/targets/blackbox-http.json
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument: $1"
        exit 1
        ;;
esac
exit 0
